apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
    - context: ../../app1/
      image: app1
  tagPolicy:
    inputDigest: {}
deploy:
  helm: {}
manifests:
  helm:
    releases:
      - chartPath: ../../charts/app
        createNamespace: true
        name: app1
        setValueTemplates:
          image.repository: '{{.IMAGE_REPO}}'
          image.tag: '{{.IMAGE_TAG}}'
